const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.gamepad,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.Car,
		C3.Plugins.AJAX,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Spritefont2.Exps.Angle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Bullet.Cnds.OnStep,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Spritefont2.Acts.ZMoveToObject,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Keyboard: 0},
	{Array: 0},
	{d_Perm: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Gamepad: 0},
	{Audio: 0},
	{Tween: 0},
	{Darkness: 0},
	{"8Direction": 0},
	{Platform: 0},
	{Car: 0},
	{Player: 0},
	{URL: 0},
	{Link: 0},
	{startX: 0},
	{Logo: 0},
	{AJAX: 0},
	{SFXSlider: 0},
	{grabbed: 0},
	{type: 0},
	{VolumePip: 0},
	{Physics: 0},
	{Wall: 0},
	{selected: 0},
	{waveid: 0},
	{righthanded: 0},
	{straight: 0},
	{lifespan: 0},
	{id: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Spirit: 0},
	{Rotate: 0},
	{Line: 0},
	{Fade: 0},
	{ghost: 0},
	{Spawner: 0},
	{cursor16: 0},
	{Sine: 0},
	{Zone: 0},
	{UIBar: 0},
	{maxlength: 0},
	{HealthBar: 0},
	{GhostIcon: 0},
	{cursor32: 0},
	{Logo2: 0},
	{Logo3: 0},
	{Logo4: 0},
	{stringlookup: 0},
	{clickable: 0},
	{secret: 0},
	{Text: 0},
	{Highlight: 0},
	{Logo5: 0},
	{Explosion: 0},
	{LightningExplosion: 0},
	{GreenBurst: 0},
	{UIOverlay: 0},
	{Brightness: 0},
	{UIHeart: 0},
	{SpaceBackground: 0},
	{Pin: 0},
	{Glitter: 0},
	{Warning: 0},
	{CameraZone: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{cursor64: 0},
	{LevelSelect: 0},
	{Checkbox: 0},
	{MenuBox: 0},
	{MusicSlider: 0},
	{Darken: 0},
	{Greg_Shadow: 0},
	{startY: 0},
	{Greg_Jaw: 0},
	{startx: 0},
	{starty: 0},
	{Greg_Eye: 0},
	{Greg_Skull: 0},
	{GregDialogue: 0},
	{Greg: 0},
	{DialogueDarken: 0},
	{Powerup: 0},
	{Radial: 0},
	{Effect: 0},
	{Color1: 0},
	{Color2: 0},
	{Color3: 0},
	{Color4: 0},
	{Color5: 0},
	{Color6: 0},
	{Transform: 0},
	{spritevfx: 0},
	{LevelSelected: 0},
	{SensPrevX: 0},
	{SensNewX: 0},
	{whereto: 0},
	{Level: 0},
	{v_morph: 0},
	{v_wave: 0},
	{v_timer: 0},
	{v_colorway: 0},
	{v_color: 0},
	{v_delay: 0},
	{v_speed: 0},
	{v_amount: 0},
	{v_straight: 0},
	{v_turnstrength: 0},
	{v_unidirectional: 0},
	{v_lifespan: 0},
	{v_ghostchance: 0},
	{v_rotationspeed: 0},
	{v_zones: 0},
	{v_trails: 0},
	{v_bg: 0},
	{v_score: 0},
	{v_health: 0},
	{v_immue: 0},
	{v_magnet: 0},
	{v_rectangle: 0},
	{v_timbo: 0},
	{v_resultopen: 0},
	{ID: 0},
	{colorvalue: 0},
	{chance: 0},
	{amount: 0},
	{damagecooldown: 0},
	{CheatString: 0},
	{Stage: 0},
	{MusicName: 0},
	{SoundName: 0},
	{RandomizePitch: 0},
	{String: 0},
	{PreviewOnly: 0},
	{TransitionSpeed: 0},
	{DestinationLayout: 0},
	{DiscordWebHookURL: 0},
	{Data: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	d_Perm: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Darkness: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Link: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	SFXSlider: class extends self.ITiledBackgroundInstance {},
	VolumePip: class extends self.ISpriteInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	Spirit: class extends self.ISpriteInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	ghost: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	cursor16: class extends self.ISpriteInstance {},
	Zone: class extends self.ISpriteInstance {},
	UIBar: class extends self.ISpriteInstance {},
	HealthBar: class extends self.ITiledBackgroundInstance {},
	GhostIcon: class extends self.ISpriteInstance {},
	cursor32: class extends self.ISpriteInstance {},
	Logo2: class extends self.ISpriteInstance {},
	Logo3: class extends self.ISpriteInstance {},
	Logo4: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	Highlight: class extends self.ITiledBackgroundInstance {},
	Logo5: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	LightningExplosion: class extends self.ISpriteInstance {},
	GreenBurst: class extends self.ISpriteInstance {},
	UIOverlay: class extends self.ISpriteInstance {},
	UIHeart: class extends self.ISpriteInstance {},
	SpaceBackground: class extends self.ISpriteInstance {},
	Glitter: class extends self.IParticlesInstance {},
	Warning: class extends self.ISpriteInstance {},
	CameraZone: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	cursor64: class extends self.ISpriteInstance {},
	LevelSelect: class extends self.ISpriteInstance {},
	Checkbox: class extends self.ISpriteInstance {},
	MenuBox: class extends self.IWorldInstance {},
	MusicSlider: class extends self.ITiledBackgroundInstance {},
	Darken: class extends self.ITiledBackgroundInstance {},
	Greg_Shadow: class extends self.ISpriteInstance {},
	Greg_Jaw: class extends self.ISpriteInstance {},
	Greg_Eye: class extends self.ISpriteInstance {},
	Greg_Skull: class extends self.ISpriteInstance {},
	GregDialogue: class extends self.ISpriteFontInstance {},
	Greg: class extends self.ISpriteFontInstance {},
	DialogueDarken: class extends self.ITiledBackgroundInstance {},
	Powerup: class extends self.ISpriteInstance {},
	Radial: class extends self.ISpriteInstance {},
	Effect: class extends self.ISpriteInstance {},
	Color1: class extends self.ISpriteInstance {},
	Color2: class extends self.ISpriteInstance {},
	Color3: class extends self.ISpriteInstance {},
	Color4: class extends self.ISpriteInstance {},
	Color5: class extends self.ISpriteInstance {},
	Color6: class extends self.ISpriteInstance {},
	Transform: class extends self.ISpriteFontInstance {},
	spritevfx: class extends self.ISpriteInstance {}
}